### ISSUE TITLE
Automate dbt source.yml for each dataset

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-extraction-loading#8]
## Example: ny_sedd_2017_chrgs.yml
```yml
version: 2

sources:
  - name: SEDD 
    tags: ['State','Emergency Department','SEDD']
    description: '{{ doc("sedd_description") }}'
    meta:
      external_location: "D:\\git\\hcup-extraction-loading\\extraction-loading\\raw-hcup\\{name}.parquet"
    tables:
      - name: NY_SEDD_2017_CHGS
        description: New York State SEDD 2017 CHGS  
```

## Thoughts 

We will need to automate the generation of these  into our dbt ./model/docs/ folder. A few things parameters:
- columns will depend on the codebooks.csv
- table name
- table description (e.g CHGS vs CORE vs HAL ... ETC)

## Action Items
- [x] operationalize dataset-file specific description
   - [x] Scrape for this source documentation: SEDD File structure: https://www.hcup-us.ahrq.gov/db/state/sedddist/SEDD_Introduction.jsp
      - [x]  2019-2021 files: https://www.hcup-us.ahrq.gov/db/state/sedddist/SEDD_Introduction.jsp#sedd5
   - [x] prototyped for sedd - core/chgs
   - [x] need to make sedd robust to years
   - [x] need to import sidd/year/files
- [x] write a function to generate source.yml files
   - [x] write YAML text
   - [x] populates dbt ./models/docs/ folder with these files
- [x] generalize to account for
   - [x] datasets (SEDD vs SID .. ETC)
   - [x] dataset-files (SEDD_CORE vs SEDD_CHGS)
   - [x] year 
- [x] Add logic to import codebooks object and operationalize column defs
